name: Continuous Integration
 
on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'
      - name: Install dependencies and run tests
        run: |
          bun install
          bun run ci:test